== Configuration del plugin

Después de instalar el plugin, simplemente activarlo es suficiente, sin embargo, hay algunos ajustes de configuración avanzada: 

** directorio de registros *: indica la ruta de acceso donde Jeedom debe poner las imágenes que captan las cámaras (es recomendable no tocar)
* *Tamaño máximo del archivo de registro (MB)* : Indica el tamaño máximo permitido para la carpeta o las capturas registradas (es recomendable no tocar). Si se sobrepasa esta cuota, Jeedom elimina las capturas más antiguas

== Configuración de dispositivos

La configuration des équipements Caméra est accessible à partir du menu plugin puis securité :

Tienes un botón de creación de dispositivos y sus cámaras actuales, con sus respectivas imágenes si están disponibles.

Haciendo clic en uno de los equipos de cámara, se obtiene:

** Nombre del dispositivo cámara *: nombre de su dispositivo cámara
** Objeto padre *: indica el objeto padre al que pertenece el dispositivo
* *Activar* : permite activar su dispositivo
* *Visible* : lo hace visible en el Dashboard
* *IP* : IP local de la cámara
* *Puerto* : El puerto con el que conectar a la cámara
* *Protocolo* : el protocolo de comunicación de la camera (http o https)
* *Usuario* : nombre de usuario para conectar a la cámara (si es necesario)
* *Contraseña* : contraseña para conectar a la cámara (si es necesario) 
* *URL de captura* : URL del "snapshot" de la cámara. Cambia en función de las cámaras. Cuidado de no poner una url de fujo directo puede colgar Jeedom. Puede utilizar las etiquetas \#username# y \#password#, que será sustituido automáticamente por el nombre de usuario y la contraseña cuando se use este comando
** frecuencia de refresco *: Frecuencia de refresco de las capturas en el widget . Atención a menor refresco mayor carga de trabajo para Jeedom.
** Enviar correo *: permite especificar un comando de correo que se utilizará para enviar capturas (comando "Enviar una captura"), puedes especificar varias direcciones separadas por &.
* *Número de captura(s) *: establece el número de capturas a enviar (las capturas se toman cada segundo)
* *Modelo* : permite elegir el modelo de la cámara, Atención cambiar esto supone sobreescribir  los parametros de configuración actuales.

A continuación encontrará la lista de ordenes :

* ID de la orden (para uso con ordenes de tipo info, por ejemplo que la cámara devuelve la información de movimiento a Jeedom a través de la api, vea abajo)
Nombre de la orden, con la posibilidad de poner un icono en el lugar (para eliminar doble clic en el icono en cuestión)
* Tipo y subtipos de ordenes
* Solicitud para enviar a la cámara para hacer una acción (cambiar a modo night, ptz,...). Puede utilizar las etiquetas \#username# y \#password#, que será sustituido automáticamente por el nombre de usuario y la contraseña cuando se use este comando
* Orden Stop : para cámaras PTZ a veces  existe un comando de Stop, aquí especificado
* Ver : Permite decidir si desea o no mostrar la orden en el dashboard
* Configuración avanzada (pequeñas ruedas dentadas): muestra la configuración avanzada de la orden (método de historico, widget...)
* Probar : le permite probar la orden
* Eliminar (signo - ) : permite borrar la orden

[IMPORTANTE]
El registro no tiene límite de tiempo y puede ocupar un montón de espacio, así que cuidado, si llena tu disco, jeedom podría dejar de verlos  a todos.

== El widget

En la imagen, captura de la cámara, ordenes definidas en la configuración, la orden para tomar una captura, la orden para iniciar la toma de captura múltiple y la orden para ver las capturas.

[TIP]
En el dashboard es posible redimensionar el widget para adaptarlo a tus necesidades

Un clique sur l'image permet d'afficher celle-ci en plus grand.

Un clique sur la derniere commande pour parcourir les captures vous affichera celle-ci.

Aquí encontraras todas las capturas organizadas por día y fecha, por cada una de ellas puedes : 

* Verla más grande pulsando sobre la imagen
* Descargarla
* Borrarla

En mobile le widget est un peu different si vous cliquez sur l'image de la camera vous obtenez celel-ci en plus grande avec les commandes possible.

== El panel

Le plugin caméra mets aussi à disposition un panel qui vous permet de voir d'un seul coup toute vos caméras, il est accessible par Acceuil -> Caméra.

[NOTE]
Pour l'avoir il faut l'activer sur la page de configuration du plugin

Por supuesto también está disponible desde el  móvil desde  Plugin -> Cámara: 

== Grabación y envío de captura

Este comando algo específico que permite después de la captura, enviarla (compatible con los plugin slack, mail y transfert)

La configuración es simple,  basta con llamar la acción de enviar captura, en el título puedes pasar más opciones (por defecto el número de captura, pero puedes ir más allá con las opciones avanzadas) y en el cuadro de mensaje, la orden del plugin (actualmente slack, mail o transfert) para realizar el envío de capturas. Puedes poner varias separados por &&

=== Opciones avanzadas de captura

* nbSnap: número de captura, si no se indica, las capturas se realizan a una petición para detener la grabación o detener la cámara
* retardo: tiempo entre 2 capturas, si no indica el período es de 1s
* wait : tiempo de espera antes de la captura, si no se indica entonces ningún envio se hará
* sendPacket: número de captura disparadas que serán enviadas, si no se indica entonces se enviarán las capturas al final.
* detectMove=1 : envoi les captures que si un changement superieur au seuil de detection (voir configuration de la caméra) arrive 
* movie=1 : une fois l'enregistrement terminé, les images sont convertie en video
* sendFirstSnap=1 : envoi la premiere capture de l'enregistrement

== Encio de la detección de movimiento a Jeedom

Si tienes una cámara que tiene detección de movimiento y quieres enviarlo a Jeedom esta es la url para poner en la cámara: 

----
http://#IP_JEEDOM#/core/api/jeeApi.php?apikey=#APIKEY#&type=camera&id=#ID#&value=#value#
----

Por supuesto antes se deben de crear un comando de tipo info en la cámara