== Configuration del plugin

Après installation du plugin, il vous suffit de l’activer, cependant il y a quelques paramètres de configuration avancée : 

* *Chemin des enregistrements* : indique le chemin où Jeedom doit stocker les images qu'il capture de vos caméras (il est déconseillé d'y toucher). Si votre chemin n'est pas dans le chemin d'installation de Jeedom alors vous ne pourrez visualiser les captures dans Jeedom.
* *Taille maximum du dossier d'enregistrement (Mo)* : indique la taille maximum autorisée pour le dossier où les captures sont enregistrées (il est déconseillé d'y toucher). Si ce quotas est atteint Jeedom supprimera les captures les plus anciennes.
* *Le plugin caméra doit réagir aux intéractions* : mots clés / phrases auxquels le plugin réagira via les intéractions de Jeedom.
* *Panel* : Vous permet d'afficher le panel (Menu Accueil > Caméra) et d'avoir une vue sur l'ensemble de vos caméras (voir plus bas)

== Configuración de dispositivos

=== Equipement

Ici vous avez les informations principales de votre caméra :

* *Nom de l’équipement caméra* : nom de votre équipement caméra
** Objeto padre *: indica el objeto padre al que pertenece el dispositivo
* *Activar* : permite activar su dispositivo
* *Visible* : lo hace visible en el Dashboard
* *IP* : l'adresse IP local de votre caméra
* *Puerto* : El puerto con el que conectar a la cámara
* *Protocole* : le protocole de communication de votre caméra (http ou https)
* *Usuario* : nombre de usuario para conectar a la cámara (si es necesario)
* *Contraseña* : contraseña para conectar a la cámara (si es necesario) 
* *URL de capture* : URL de "snapshot" de la caméra. Change en fonction des caméras. Attention à ne pas mettre une url de flux sous peine de planter Jeedom. Vous pouvez ajouter les tags \#username# et \#password#, qui seront automatiquement remplacé par le nom d'utilisateur et le mot de passe lors de l'utilisation de cette commande
* *Modèle* : permet de choisir le modèle de la caméra. Attention si vous changez cela écrasera vos paramètres de configuration

=== Images

Cette partie vous permets de configurer la qualité de l'image. En effet Jeedom diminue la taille de l'image ou la compresse avant de l'envoyer à votre navigateur. Cela permet de gagner en fluidité des images (car elles sont moins lourde). C'est aussi dans cette partie que vous pouvez configurer le nombre d'image par secondes à afficher. 
Tous les réglages sont déclinés en : mobile/desktop et miniature/normal.

* Rafraichissement (s) : délai en seconde entre l'affichage de 2 images (vous pouvez ici mettre des chiffre inférieure à 1)
* Compression (%) : plus il est faible moins on compresse l'image, à 100% aucune compression n'est faite
* Taille (% - 0 : automatique) : plus le % est élévé plus on est proche de la taille d'origine de l'image. A 100% aucun redimensionnement de l'image n'a lieu

[NOTE]
Si vous mettez une compression de 0% et une taille de 100% Jeedom ne touchera pas à l'image en mode normal. Cela n'est pas valable en mode miniature ou il y a une taille maximum de l'image de 360px.

=== Capture

* Durée maximum d'un enregistrement (s) : durée maximum des enregistrements
* Toujours faire une video : force Jeedom à toujours transformer les enregistrements en video avant l'enregistrement
* Nombre d'images par seconde de la vidéo : nombre d'images par seconde des vidéos
* Seuil de détection mouvement (0-100) : seuil de détection de mouvement (il est conseillé de mettre 2). Plus la valeur est grande plus la sensibilité augmente.
* Supprimer toutes les captures de la caméra : supprime toutes les captures et enregistrements de la caméra

=== Alimentation

* Commande ON : Commande permetant de mettre en marche l'alimentation de la caméra
* Commande OFF : Commande permetant de couper l'alimentation de la caméra

=== Commandes

* ID de la commande (utiliser avec les commandes de type info pour par exemple remonter l'information de mouvement de la caméra à Jeedom par l'api, voir plus bas)
Nombre de la orden, con la posibilidad de poner un icono en el lugar (para eliminar doble clic en el icono en cuestión)
* Tipo y subtipos de ordenes
* Requête à envoyer à la caméra pour faire une action (passage en mode nuit, ptz, etc.). Vous pouvez utiliser les tags \#username# et \#password#, qui seront automatiquement remplacé par le nom d'utilisateur et le mot de passe lors de l'utilisation de cette commande
* Commande stop : pour les caméras PTZ il existe souvent une commande qui arrête le mouvement, c'est ici qu'il faut la spécifier
* Ver : Permite decidir si desea o no mostrar la orden en el dashboard
* Configuration avancée (petites roues crantées) : permet d'afficher la configuration avancée de la commande (méthode d'historisation, widget, etc.)
* Probar : le permite probar la orden
* Eliminar (signo - ) : permite borrar la orden

== El widget

On retrouve sur celui-ci l'image de la caméra, les commandes définies dans la configuration, la commande pour prendre une capture, la commande pour lancer la prise de multiples captures images et la commande pour parcourir ces captures.

[TIP]
En el dashboard es posible redimensionar el widget para adaptarlo a tus necesidades

Un clique sur l'image permet d'afficher celle-ci dans une fenêtre et dans un format plus grand.

Un clique sur la dernière commande pour parcourir les captures vous affichera celle-ci.

Vous retrouvez ici toutes les captures organisées par jour puis par date, vous pouvez pour chacune d'elle : 

* Verla más grande pulsando sobre la imagen
* Descargarla
* Borrarla

En mobile le widget est un peu différent si vous cliquez sur l'image de la caméra vous obtenez celle-ci en plus grande avec les commandes possibles.

== El panel

Le plugin caméra met aussi à disposition un panel qui vous permet de voir d'un seul coup toutes vos caméras, il est accessible par Acceuil -> Caméra.

[NOTE]
Pour l'avoir il faut l'activer sur la page de configuration du plugin

Por supuesto también está disponible desde el  móvil desde  Plugin -> Cámara: 

== Grabación y envío de captura

Cette commande un peu spécifique permet suite à la prise de capture de faire l'envoi de celle-ci (compatible avec le plugin slack, mail et transfert)

La configuración es simple,  basta con llamar la acción de enviar captura, en el título puedes pasar más opciones (por defecto el número de captura, pero puedes ir más allá con las opciones avanzadas) y en el cuadro de mensaje, la orden del plugin (actualmente slack, mail o transfert) para realizar el envío de capturas. Puedes poner varias separados por &&

=== Opciones avanzadas de captura

* nbSnap: número de captura, si no se indica, las capturas se realizan a una petición para detener la grabación o detener la cámara
* retardo: tiempo entre 2 capturas, si no indica el período es de 1s
* wait : tiempo de espera antes de la captura, si no se indica entonces ningún envio se hará
* sendPacket: número de captura disparadas que serán enviadas, si no se indica entonces se enviarán las capturas al final.
* detectMove=1 : envoi les captures que si un changement superieur au seuil de detection (voir configuration de la caméra) arrive 
* movie=1 : une fois l'enregistrement terminé, les images sont convertie en video
* sendFirstSnap=1 : envoi la premiere capture de l'enregistrement

== Encio de la detección de movimiento a Jeedom

Si vous avez une caméra qui possède la détection de mouvement et que vous voulez transmettre celle-ci à Jeedom voilà l'url à mettre sur votre caméra : 

----
http://#IP_JEEDOM#/core/api/jeeApi.php?apikey=#APIKEY#&type=camera&id=#ID#&value=#value#
----

Il faut bien entendu avant avoir créé une commande de type info sur votre caméra