name : 'Php 7.3'

on:
  push:
    branches:
      - beta
    paths:
      - "**.php"
  pull_request:
    branches:
      - beta
      - master
    paths:
      - "**.php"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@v1
        with:
          folder-to-exclude: "! -path \"./3rdparty/*\""
