name: "PHP"

on:
  push:
    branches:
      - beta
    paths:
      - "**.php"
  pull_request:
    branches:
      - beta
      - master
    paths:
      - "**.php"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: michaelw90/PHP-Lint@master

      
